Books = [
    [ // textbook
        "Lesson 7",
        "Lesson 8",
        "Lesson 9",
        "Review 3"
    ],
    [ // magazine
        "5/13~14",
        "5/15~16",
        "5/17~18",
        "5/20~21",
        "5/22~23",
        "5/24~25",
        "5/27~28",
        "6/1",
        "6/3~4",
        "6/5~6"
    ],
    [ // stupid book
        "Unit 22",
        "Unit 23",
        "Unit 24",
    ]
]

words = [
    [ // textbook
        [ // Lesson 7
            ["seek", ["尋找", "尋求"]],
            ["series", ["系列"]],
            ["foundation", ["基金會"]],
            ["found", ["創立", "建設"]],
            ["technology", ["科技"]],
            ["technological", ["科技的"]],
            ["conference", ["會議", "研討會"]],
            ["worth", ["值得", "價值", "意義"]],
            ["worthy", ["值得的"]],
            ["increasingly", ["愈來愈..."]],
            ["increase", ["增加"]],
            ["organizer", ["組織者", "籌辦者"]],
            ["organize", ["組織"]],
            ["organization", ["機構", "組織"]],
            ["broad", ["廣泛的", "寬闊的"]],
            ["broaden", ["拓展"]],
            ["range", ["範圍", "種類", "系列"]],
            ["field", ["領域"]],
            ["philosophy", ["哲學"]],
            ["launch", ["發起", "發行"]],
            ["collection", ["收藏品", "一堆"]],
            ["collect", ["收集", "收取"]],
            ["numerous", ["很多的"]],
            ["celebrity", ["名人"]],
            ["audience", ["觀眾", "聽眾"]],
            ["fascination", ["吸引力", "著迷"]],
            ["fascinate", ["使人著迷", "吸引", "著迷"]],
            ["fiction", ["小說"]],
            ["discuss", ["討論", "闡述", "探討"]],
            ["discussion", ["討論"]],
            ["method", ["方法"]]
        ],
        [ // Lesson 8
            ["exchange", ["交換", "交流"]],
            ["expect", ["預期"]],
            ["expectation", ["期望", "預期"]],
            ["shelter", ["庇護處", "遮蔽"]],
            ["fierce", ["激烈的", "強烈的"]],
            ["occupy", ["佔據", "佔領"]],
            ["occupation", ["職業"]],
            ["vehicle", ["交通工具", "車輛"]],
            ["temporary", ["暫時的", "臨時的"]],
            ["assistant", ["助理", "助手"]],
            ["assist", ["幫助"]],
            ["assistance", ["幫助"]],
            ["originate", ["起源於"]],
            ["origin", ["起源"]],
            ["original", ["原本的"]],
            ["event", ["事件"]],
            ["elder", ["長輩", "較為年長的"]],
            ["elderly", ["年紀大的"]],
            ["neighborhood", ["鄰近地區"]],
            ["cooperate", ["合作"]],
            ["cooperation", ["合作"]],
            ["arrange", ["安排"]],
            ["arrangement", ["安排"]],
            ["relax", ["放鬆"]],
            ["container", ["容器"]],
            ["contain", ["包含"]],
            ["stroll", ["散步"]],
            ["spirit", ["靈魂", "精神"]],
            ["spirital", ["精神上的"]]
        ],
        [ // Lesson 9
            ["general", ["一般的", "非專門的"]],
            ["derive", ["起源於", "得到", "獲得"]],
            ["release", ["釋放", "發行", "排放"]],
            ["feature", ["特徵", "特色", "特點"]],
            ["gossip", ["八卦", "流言", "散布流言", "說八卦"]],
            ["reveal", ["洩漏", "透露"]],
            ["chase", ["追逐"]],
            ["brand", ["品牌"]],
            ["image", ["形象", "影像"]],
            ["edit", ["編輯"]],
            ["edition", ["版本"]],
            ["modify", ["修改"]],
            ["modification", ["修改"]],
            ["digitally", ["數位地"]],
            ["digital", ["數位的"]],
            ["combine", ["結合"]],
            ["combination", ["結合"]],
            ["standard", ["標準", "標準的"]],
            ["widespread", ["廣泛的"]]
            ["usage", ["用法"]],
            ["constantly", ["持續地"]],
            ["constant", ["持續的"]],
            ["alternative", ["另類的", "非傳統的", "替代的", "替代方案"]],
            ["exist", ["存在"]],
            ["existence", ["存在"]],
        ],
        [ // Review 3
            ["astronaut", ["太空人"]],
            ["gravity", ["重力"]],
            ["powdered", ["粉狀的", "製成粉的"]],
            ["liquid", ["液體的"]],
            ["regularly", ["規律地"]],
            ["tend", ["往往會"]],
            ["gather", ["聚集"]],
            ["vision", ["視力"]],
            ["decrease", ["減少"]],
            ["limit", ["限制"]],
            ["physical", ["生理上的"]],
            ["circulation", ["血液循環"]],
            ["maintain", ["維持"]],
            ["sweat",["汗水"]],
            ["ohterwise", ["否則"]],
            ["bump", ["碰撞"]],
            ["ISS", ["國際太空站"]],
            ["sacrifice", ["犧牲"]],
        ]
    ],
    [ // magazine
        [ // 5/13~14
            ["virtually", ["虛擬地"]],
            ["virtual reality", ["虛擬實境"]],
            ["geographical", ["地理的"]],
            ["rotate", ["旋轉", "轉動"]],
            ["credible", ["可信的", "可靠的"]],
            ["preview", ["預覽"]],
            ["dazzle", ["使讚嘆"]],
            ["accommodations", ["住宿"]],
            ["inaccessible", ["無法去的"]],
            ["accessibility", ["可到達", "易觸及"]],
            ["with open arms", ["迎接"]],
            ["foster", ["促進", "培養"]],
            ["monoscopic", ["單一視野的"]],
            ["stereoscopic", ["有立體感的"]]
        ],
        [ // 5/15~16
            ["flexible", ["靈活的", "有彈性的"]],
            ["cautious", ["謹慎的", "小心翼翼的"]],
            ["confuse", ["使困惑"]],
            ["intimate", ["親密的"]],
            ["chat", ["聊天"]],
            ["tolerate", ["容忍"]],
            ["mall", ["購物中心"]],
            ["instinct", ["直覺", "本能"]],
            ["confusion", ["迷惑不解"]],
            ["confusingly", ["令人困惑地"]],
            ["substitute", ["替代品"]],
            ["red flag", ["示警紅旗"]]
        ],
        [ // 5/17~18
            ["illustrious", ["著名的"]],
            ["chef", ["主廚"]],
            ["courteous", ["謙恭有禮的"]],
            ["luxurious", ["豪華的", "奢華的"]],
            ["presentation", ["報告", "介紹"]],
            ["ruin", ["廢墟", "殘垣斷壁"]],
            ["glimpse", ["一瞥"]],
            ["arena", ["競技場", "比賽場"]],
            ["massive", ["巨大的"]],
            ["glacier", ["冰河"]],
            ["resident", ["居民"]],
            ["alpine", ["高山的"]],
            ["excursion", ["短期旅行"]],
            ["amphitheater", ["圓形劇場"]],
            ["gorge", ["峽谷"]]
        ],
        [ // 5/20~21
            ["icy", ["結冰的", "極冷的"]],
            ["owl", ["貓頭鷹"]],
            ["bud", ["花蕾", "葉芽"]],
            ["dam", ["水壩"]],
            ["fur", ["毛皮"]],
            ["reputation", ["名譽"]],
            ["convince", ["說服"]],
            ["eventually", ["最終", "終於"]],
            ["remind", ["提醒"]],
            ["delicate", ["嬌嫩的", "脆弱的"]],
            ["eventual", ["最終的"]],
            ["eventuality", ["不測事件"]],
            ["lofty", ["高的"]],
            ["ensure", ["確保"]],
            ["mischievous", ["惡作劇的"]],
            ["elusive", ["難以找到的"]],
            ["exploration", ["探索"]]
        ],
        [ // 5/22~23
            ["posture", ["姿勢"]],
            ["subtle", ["細微的"]],
            ["outright", ["公然", "完全"]],
            ["misinterpret", ["誤解"]],
            ["discomfort", ["不適", "不安"]],
            ["displeasure", ["不悅"]],
            ["conceal", ["隱藏"]],
            ["proximity", ["接近", "親近"]],
            ["slump", ["坐下"]],
            ["interact", ["互動"]],
            ["come to mid", ["浮現腦海"]],
            ["baseline", ["基線"]]
        ],
        [ // 5/24~25
            ["sensation", ["轟動的事件"]],
            ["racket", ["球拍"]],
            ["acquaint", ["使熟悉"]],
            ["mentally", ["思想上", "心裡上"]],
            ["astound", ["使震驚"]],
            ["accomplishment", ["成就", "成績"]],
            ["tense", ["緊張的"]],
            ["stumble", ["絆倒"]],
            ["spectator", ["觀眾"]],
            ["defeat", ["擊敗"]],
            ["meteoric", ["發展迅速的"]]
        ],
        [ // 5/27~28
            ["contradiction", ["矛盾"]],
            ["stagger", ["使震驚"]],
            ["reliant", ["依賴的"]],
            ["render", ["使成為", "使變得"]],
            ["starvation", ["飢餓", "挨餓"]],
            ["diversify", ["使多樣化"]],
            ["eradicate", ["根除", "消滅"]],
            ["coordinate", ["協調"]],
            ["quest", ["尋求"]],
            ["nutrient", ["營養"]],
            ["blight", ["疾病"]],
            ["cyclone", ["氣旋"]]
        ],
        [ // 6/1
            ["doughnut", ["甜甜圈"]],
            ["crispy", ["酥脆的"]],
            ["raw", ["生的"]],
            ["punch", ["在...打孔", "打孔器"]],
            ["bacon", ["培根"]],
            ["punchy", ["頭昏眼花的"]],
            ["punch line", ["笑點", "梗"]],
            ["dough", ["麵團"]],
            ["deep-fry", ["油炸"]],
            ["glaze", ["糖汁"]]
        ],
        [ // 6/3~4
            ["categorize", ["將...分類"]],
            ["external", ["外部的"]],
            ["workforce", ["勞動人口"]],
            ["extensively", ["廣泛地"]],
            ["hybird", ["混合"]],
            ["pandemic", ["大流行病"]],
            ["correlate", ["相關", "聯繫"]],
            ["invaluable", ["極有用的", "寶貴的"]],
            ["that is", ["確切來說"]],
            ["thrive", ["茁壯成長"]],
            ["mindest", ["心態", "思維方式"]]
        ],
        [ // 6/5~6
            ["stunning", ["極漂亮的"]],
            ["wildlife", ["野生生物"]],
            ["classification", ["分類", "類別"]],
            ["frequently", ["經常地"]],
            ["conservation", ["保育", "保護"]],
            ["informative", ["提供資訊的", "增長見聞的"]],
            ["highlight", ["精彩的部份"]],
            ["exotic", ["異國風情的", "奇異的"]],
            ["sustainable", ["可持續的"]],
            ["exhibit", ["展覽"]],
            ["archipelago", ["群島"]],
            ["geological", ["地質的"]],
            ["rainforest", ["雨林"]],
            ["sea level", ["海平面"]]
        ]
    ],
    [ // stupid book 
        [ // Unit 22
            ["chimney", ["煙囪"]],
            ["chip", ["晶片", "薯片", "薄片", "弄缺", "打碎"]],
            ["discount", ["折扣", "忽視"]],
            ["account", ["帳號", "藉口"]],
            ["faucet", ["水龍頭"]],
            ["gossip", ["八卦", "流言蜚語", "聊八卦"]],
            ["heap", ["一堆", "堆積"]],
            ["melt", ["融化"]],
            ["freeze", ["冰凍", "凍結"]],
            ["minus", ["減去"]],
            ["pearl", ["珍珠"]],
            ["penny", ["一分錢"]],
            ["proof", ["證明", "證據"]],
            ["evidence", ["證據"]],
            ["pub", ["酒吧"]],
            ["punch", ["擊打", "打孔"]],
            ["razor",["剃刀", "刮鬍刀"]],
            ["rug", ["小地毯", "地墊"]],
            ["scrub", ["刷洗", "擦洗"]],
            ["seal", ["密封", "海豹"]],
            ["slave", ["奴隸"]],
            ["sleeve", ["袖子"]],
            ["sleeveless", ["無袖的"]],
            ["slice", ["切片", "薄片"]],
            ["slippery", ["滑的"]],
            ["slip", ["滑倒", "小紙條"]],
            ["slope", ["斜面", "斜坡"]],
            ["snap", ["拉斷", "大聲說話", "發怒", "劈啪聲"]],
            ["snapshot", ["快照"]],
            ["summit", ["峰頂", "高峰會"]],
            ["peak", ["山頂"]],
            ["submit", ["提交"]],
            ["swear", ["發誓", "咒罵"]],
            ["sweat", ["汗水", "流汗"]],
            ["swell", ["腫脹"]],
            ["swollen", ["腫脹的"]],
            ["swift", ["迅速的", "即時的"]],
            ["swiftly", ["迅速地"]],
            ["sword", ["劍"]],
            ["voter", ["選民"]],
            ["vote", ["投票"]]
        ],
        [ // Unit 23
            ["acceptable", ["可接受的"]],
            ["acceptance", ["接受"]],
            ["unacceptable", ["無法接受的"]],
            ["accept", ["接受"]],
            ["bead", ["珠子", "小水滴"]],
            ["brass", ["黃銅"]],
            ["bravery", ["勇氣", "勇敢"]],
            ["courage", ["勇氣", "勇敢"]],
            ["brave", ["勇敢的"]],
            ["breast", ["胸部", "乳房"]],
            ["chest", ["胸膛", "胸腔"]],
            ["beast", ["野獸"]],
            ["cigarette", ["香煙"]],
            ["ciger", ["雪茄"]],
            ["circus", ["馬戲團"]],
            ["client", ["客戶", "委託人"]],
            ["customer", ["顧客"]],
            ["clinic", ["診所"]],
            ["dislike", ["不喜歡", "厭惡"]],
            ["enjoyable", ["令人愉快的", "有趣的"]],
            ["enjoyment", ["享受", "樂趣"]],
            ["feather", ["羽毛"]],
            ["governor", ["州長"]],
            ["government", ["政府"]],
            ["govern", ["管理", "治理"]],
            ["heel", ["後腳跟"]],
            ["hell", ["地獄"]],
            ["hug", ["擁抱"]],
            ["lifetime", ["一生"]],
            ["lighthouse", ["燈塔"]],
            ["lollipop", ["棒棒糖"]],
            ["lord", ["君主", "統治者"]],
            ["mend", ["修補", "好轉", "康復"]],
            ["fix", ["修補"]],
            ["repair", ["修補"]],
            ["mob", ["暴民"]],
            ["mop", ["拖把"]],
            ["monk", ["僧侶"]],
            ["priest", ["神父", "牧師"]],
            ["occasion", ["場合", "偶爾的"]],
            ["pine", ["松樹", "松木"]],
            ["tease", ["朝弄", "嘲笑"]],
            ["timber", ["木材"]],
            ["tobacco", ["菸草"]],
            ["vase", ["花瓶"]],
            ["vest", ["背心"]]
        ],
        [ // Unit 24
            ["ash", ["灰燼"]],
            ["awful", ["糟糕的"]],
            ["breeze", ["微風"]],
            ["bride", ["新娘"]],
            ["bullet", ["子彈"]],
            ["ballet", ["芭蕾舞"]],
            ["bunch", ["束"]],
            ["cocktail", ["雞尾酒"]],
            ["coconut", ["椰子"]],
            ["collar", ["領子"]],
            ["crispy", ["酥脆的"]],
            ["crown", ["皇冠"]],
            ["ditch", ["壕溝", "水溝"]],
            ["dive", ["跳水"]],
            ["drown", ["溺死", "溺水"]],
            ["envy", ["羨慕", "嫉妒"]],
            ["fist", ["拳頭"]],
            ["flame", ["火焰"]],
            ["pit", ["深洞", "窪坑", "果核"]],
            ["plenty", ["豐富", "充分"]],
            ["plentiful", ["大量的", "充足的"]],
            ["poverty", ["貧窮"]],
            ["receipt", ["收據", "接收"]],
            ["receiver", ["接收者", "話筒"]],
            ["reception", ["接待", "歡迎", "服務台"]],
            ["receive", ["收到", "接到"]],
            ["someday", ["有一天"]],
            ["sometime", ["某個時候"]],
            ["sometimes", ["偶爾", "有時候"]],
            ["spaghetti", ["義大利麵"]],
            ["spice", ["香料", "加香料"]],
            ["spicy", ["辣的"]],
            ["spill", ["溢出", "灑出"]],
            ["toss", ["投擲", "向後甩"]],
            ["tutor", ["家教", "擔任家教"]],
            ["verse", ["詩", "韻文", "詩詞", "詩句"]],
            ["wagon", ["四輪馬車"]]
        ]
    ],
];

quizHTML = "<br><br><br><button id = \"incorcnt\"><i class=\"fa-regular fa-face-smile\"></i></button><span id = \"content\"></span><button id = \"correctcnt\"><i class=\"fa-solid fa-check\"></i> 0/0</button><br><br><br><button id = \"A\" class = \"op\">a</button><br><button id = \"B\" class = \"op\">b</button><br><button id = \"C\" class = \"op\">c</button><br><button id = \"D\" class = \"op\">d</button><span id = \"WA\"></span>"
mainHTML = "<button id = \"start\"><strong>開始測驗</strong></button><br><br><div id = \"options\"><button id = \"option0\" class = \"Button\">課本</button><br><button id = \"option1\" class = \"Button\">雜誌</button><br><button id = \"option2\" class = \"Button\">字彙王</button></div>"