Books = [
    [ // textbook
        "Lesson 7",
        "Lesson 8",
        "Lesson 9",
        "Review 3"
    ],
    [ // maganize

    ],
    [ // stupid book
        "Unit 22"
    ]
]

words = [
    [ // textbook
        [
            ["seek", ["尋找", "尋求"]],
            ["series", ["系列"]],
            ["foundation", ["基金會"]],
            ["found", ["創立", "建設"]],
            ["technology", ["科技"]],
            ["technological", ["科技的"]],
            ["conference", ["會議", "研討會"]],
            ["worth", ["值得", "價值", "意義"]],
            ["wotrhy", ["值得的"]],
            ["increasingly", ["愈來愈..."]],
            ["increase", ["增加"]],
            ["organizer", ["組織者", "籌辦者"]],
            ["organize", ["組織"]],
            ["organization", ["機構", "組織"]],
            ["broad", ["廣泛的", "寬闊的"]],
            ["broaden", ["拓展"]],
            ["range", ["範圍", "種類", "系列"]],
            ["field", ["領域"]],
            ["philosophy", ["哲學"]],
            ["launch", ["發起", "發行"]],
            ["collection", ["收藏品", "一堆"]],
            ["collect", ["收集", "收取"]],
            ["numerous", ["很多的"]],
            ["celebrity", ["名人"]],
            ["audience", ["觀眾", "聽眾"]],
            ["fascination", ["吸引力", "著迷"]],
            ["fascinate", ["使人著迷", "吸引", "著迷"]],
            ["fiction", ["小說"]],
            ["discuss", ["討論", "闡述", "探討"]],
            ["discussion", ["討論"]],
            ["method", ["方法"]]
        ],
        [
            ["exchange", ["交換", "交流"]],
            ["expect", ["預期"]],
            ["expectation", ["期望", "預期"]],
            ["shelter", ["庇護處", "遮蔽"]],
            ["fierce", ["激烈的", "強烈的"]],
            ["occupy", ["佔據", "佔領"]],
            ["occupation", ["職業"]],
            ["vehicle", ["交通工具", "車輛"]],
            ["temporary", ["暫時的", "臨時的"]],
            ["assistant", ["助理", "助手"]],
            ["assist", ["幫助"]],
            ["assistance", ["幫助"]],
            ["originate", ["起源於"]],
            ["origin", ["起源"]],
            ["original", ["原本的"]],
            ["event", ["事件"]],
            ["elder", ["長輩", "較為年長的"]],
            ["elderly", ["年紀大的"]],
            ["neighborhood", ["鄰近地區"]],
            ["cooperate", ["合作"]],
            ["cooperation", ["合作"]],
            ["arrange", ["安排"]],
            ["arrangement", ["安排"]],
            ["relax", ["放鬆"]],
            ["container", ["容器"]],
            ["contain", ["包含"]],
            ["stroll", ["散步"]],
            ["spirit", ["靈魂", "精神"]],
            ["spirital", ["精神上的"]]
        ],
        [
            ["general", ["一般的", "非專門的"]],
            ["derive", ["起源於", "得到", "獲得"]],
            ["release", ["釋放", "發行", "排放"]],
            ["feature", ["特徵", "特色", "特點"]],
            ["gossip", ["八卦", "流言", "散布流言", "說八卦"]],
            ["reveal", ["洩漏", "透露"]],
            ["chase", ["追逐"]],
            ["brand", ["品牌"]],
            ["image", ["形象", "影像"]],
            ["edit", ["編輯"]],
            ["edition", ["版本"]],
            ["modify", ["修改"]],
            ["modification", ["修改"]],
            ["digitally", ["數位地"]],
            ["digital", ["數位的"]],
            ["combine", ["結合"]],
            ["combination", ["結合"]],
            ["standard", ["標準", "標準的"]],
            ["widespread", ["廣泛的"]]
            ["usage", ["用法"]],
            ["constantly", ["持續地"]],
            ["constant", ["持續的"]],
            ["alternative", ["另類的", "非傳統的", "替代的", "替代方案"]],
            ["exist", ["存在"]],
            ["existence", ["存在"]],
        ],
        [
            ["astronaut", ["太空人"]],
            ["gravity", ["重力"]],
            ["powdered", ["粉狀的", "製成粉的"]],
            ["liquid", ["液體的"]],
            ["regularly", ["規律地"]],
            ["tend", ["往往會"]],
            ["gather", ["聚集"]],
            ["vision", ["視力"]],
            ["decrease", ["減少"]],
            ["limit", ["限制"]],
            ["physical", ["生理上的"]],
            ["circulation", ["血液循環"]],
            ["maintain", ["維持"]],
            ["sweat",["汗水"]],
            ["ohterwise", ["否則"]],
            ["bump", ["碰撞"]],
            ["ISS", ["國際太空站"]],
            ["sacrifice", ["犧牲"]],
        ]
    ],
    [ // maganize

    ],
    [ // stupid book 
        [
            ["chimney", ["煙囪"]],
            ["chip", ["晶片", "薯片", "薄片", "弄缺", "打碎"]],
            ["discount", ["折扣", "忽視"]],
            ["account", ["帳號", "藉口"]],
            ["faucet", ["水龍頭"]],
            ["gossip", ["八卦", "流言蜚語", "聊八卦"]],
            ["heap", ["一堆", "堆積"]],
            ["melt", ["融化"]],
            ["freeze", ["冰凍", "凍結"]],
            ["minus", ["減去"]],
            ["pearl", ["珍珠"]],
            ["penny", ["一分錢"]],
            ["proof", ["證明", "證據"]],
            ["evidence", ["證據"]],
            ["pub", ["酒吧"]],
            ["punch", ["擊打", "打孔"]],
            ["razor",["剃刀", "刮鬍刀"]],
            ["rug", ["小地毯", "地墊"]],
            ["scrub", ["刷洗", "擦洗"]],
            ["seal", ["密封", "海豹"]],
            ["slave", ["奴隸"]],
            ["sleeve", ["袖子"]],
            ["sleeveless", ["無袖的"]],
            ["slice", ["切片", "薄片"]],
            ["slippery", ["滑的"]],
            ["slip", ["滑倒", "小紙條"]],
            ["slope", ["斜面", "斜坡"]],
            ["snap", ["拉斷", "大聲說話", "發怒", "劈啪聲"]],
            ["snapshot", ["快照"]],
            ["summit", ["峰頂", "高峰會"]],
            ["peak", ["山頂"]],
            ["submit", ["提交"]],
            ["swear", ["發誓", "咒罵"]],
            ["sweat", ["汗水", "流汗"]],
            ["swell", ["腫脹"]],
            ["swollen", ["腫脹的"]],
            ["swift", ["迅速的", "即時的"]],
            ["swiftly", ["迅速地"]],
            ["sword", ["劍"]],
            ["voter", ["選民", "投票"]]
        ]
    ]
];

quizHTML = "<br><br><br><button id = \"incorcnt\">0</button><span id = \"content\"></span><button id = \"correctcnt\">0</button><br><br><br><button id = \"A\" class = \"op\">a</button><br><button id = \"B\" class = \"op\">b</button><br><button id = \"C\" class = \"op\">c</button><br><button id = \"D\" class = \"op\">d</button><span id = \"WA\"></span>"